# .coderabbit.yml - CodeRabbit configuration file for React Vite project

# Core configuration
version: 1
reviews:
  request_changes_threshold: "major"
  approve_threshold: "minor"
  review_status: true

# Customize what files CodeRabbit should analyze
files:
  include:
    - "src/**/*.{js,jsx,ts,tsx}"
    - "*.{js,jsx,ts,tsx,json}"
    - "public/**/*"
    - "vite.config.{js,ts}"
    - "index.html"
    - "package.json"

  exclude:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "coverage/**"
    - "**/*.test.{js,jsx,ts,tsx}"
    - "**/*.spec.{js,jsx,ts,tsx}"
  
# Configure analysis settings
analysis:
  categories:
    - security
    - performance
    - bug_prevention
    - code_style
    - best_practices

  react:
    enabled: true
    best_practices: true
    hooks: true
    jsx: true
    
  eslint:
    enabled: true
    
  typescript:
    enabled: true
    
  vite:
    enabled: true

# PR comment settings
comments:
  max_number_of_reviews: 10
  max_line_length: 500
  sections:
    - summary
    - security
    - performance
    - code_improvements